### ISSUE TITLE
当数据量过少时会出现崩溃问题 

### ISSUE THREAD

**Issue by a1265137718** [gzw19931217/android-kline#4]
Process: com.guoziwei.kline, PID: 12886
                                                                    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                        at java.util.ArrayList.get(ArrayList.java:308)
                                                                        at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
                                                                        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
                                                                        at com.guoziwei.klinelib.chart.LineChartRenderer.drawValues(LineChartRenderer.java:551)
                                                                        at com.guoziwei.klinelib.chart.AppCombinedChartRenderer.drawValues(AppCombinedChartRenderer.java:96)
                                                                        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
                                                                        at android.view.View.draw(View.java:14465)
                                                                        at android.view.View.getDisplayList(View.java:13362)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.View.draw(View.java:14182)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                        at android.view.View.getDisplayList(View.java:13357)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.View.draw(View.java:14182)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                        at android.view.View.getDisplayList(View.java:13357)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.View.draw(View.java:14182)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                        at android.view.View.getDisplayList(View.java:13357)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.View.draw(View.java:14182)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                        at android.view.View.getDisplayList(View.java:13357)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.View.draw(View.java:14182)
                                                                        at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
                                                                        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
                                                                        at android.view.View.draw(View.java:14468)
                                                                        at android.support.v4.view.ViewPager.draw(ViewPager.java:2418)
                                                                        at android.view.View.getDisplayList(View.java:13362)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                        at android.view.View.getDisplayList(View.java:13300)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                        at android.view.View.getDisplayList(View.java:13300)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                        at android.view.View.getDisplayList(View.java:13300)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                        at android.view.View.getDisplayList(View.java:13300)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                        at android.view.View.getDisplayList(View.java:13300)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3077)
                                                                        at android.view.View.getDisplayList(View.java:13300)
                                                                        at android.view.View.getDisplayList(View.java:13404)
                                                                        at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
                                                                        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2405)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2277)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1907)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                    	at and

**Comment by a1265137718** [comment]
问题出现的K线图 其他图标暂不清楚

**Comment by TJHello** [comment]
怎么解决，是数量的问题还是数据不对的问题？

**Comment by gzw19931217** [comment]
1.0.2版本已修复，原因可参考https://github.com/PhilJay/MPAndroidChart/issues/2455

**Comment by a1265137718** [comment]
老哥 ,稳
